name: Autograding Tests
on:
  push:
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
    - name: Run program
      id: run-program
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Run program
        command: make run
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUN-PROGRAM_RESULTS: "${{steps.run-program.outputs.result}}"
      with:
        runners: run-program
